### ISSUE TITLE
yarn add @salesforce/cli not working as expected

### ISSUE THREAD

**Issue by nhall97** [salesforcecli/cli#50]
### Summary

Trying to use yarn to add dependency @Salesforce/cli dependency, does not register the commands.

### Steps To Reproduce:

1.  Git clone this basic yarn repo: https://github.com/nhall97/salesforce-cli-pipeline
1. ```$yarn install```
1. ```$sf help```

### Expected result
Expect output of help command from Salesforce

### Actual result
1. ```$ bash: sf: command not found```

### System Information
Not possible - command not found

### Additional information

_Feel free to attach a screenshot_.

**Comment by mdonnalley** [comment]
@nhall97 npm and yarn don't install binaries globally whenever you do a local install.

If you want `sf` to be available globally, you should run `npm install -g @salesforce/cli`. Otherwise, you'll need to execute `sf` using yarn, e.g. `yarn sf --help`

```
~/salesforce-cli-pipeline [main] : yarn sf --help
yarn run v1.22.5
$ /Users/mdonnalley/salesforce-cli-pipeline/node_modules/.bin/sf --help
sf is in beta.

The Salesforce CLI

VERSION
  @salesforce/cli/0.0.38 darwin-x64 node-v14.15.4

USAGE
  $ sf [COMMAND]

TOPICS
  commandreference  generate the Salesforce CLI command reference guide.
  config            Commands to configure Salesforce CLI.
  deploy            Commands to deploy artifacts to an environment.
  env               Commands to manage your environments, such as orgs.
  login             Commands to log in to an environment.
  logout            Commands to log out of an environment.
  plugins           list installed plugins
  retrieve          Commands to retrieve artifacts from an environment.

COMMANDS
  deploy   Deploy a project interactively to any Salesforce environment.
  help     display help for sf
  login    Log interactively into an environment, such as a Salesforce org.
  logout   Log out of all environments, such as Salesforce orgs and compute environments.
  plugins  list installed plugins
```
